version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
